#!/usr/bin/env node
/**
 * Supernal Interface MCP Server
 * Auto-generated by: si setup-mcp
 * 
 * Exposes your application's @Tool decorated methods to AI assistants
 * via the Model Context Protocol (MCP).
 * 
 * Compatible with:
 * - Claude Desktop
 * - Cursor IDE  
 * - Custom MCP clients
 */

const path = require('path');
const __projectRoot = __dirname;

// Silence all console.log during tool loading (MCP uses stdout for JSON-RPC)
const originalLog = console.log;
const originalWarn = console.warn;
console.log = () => {};
console.warn = () => {};

const { createSupernalMCPServer, createStdioTransport } = require('@supernal/interface/mcp-server');

// Use ts-node to load TypeScript sources directly with absolute path
require('ts-node').register({
  project: path.join(__projectRoot, 'tsconfig.mcp.json'),
  transpileOnly: true
});

// Import and register all tools from the application
async function loadTools() {
  try {
    console.error('[Supernal MCP] Loading tools from TypeScript sources...');
    
    // Import central tool registry (auto-registers all tools)
    require(path.join(__projectRoot, 'src/tools/index.ts'));
    
    console.error('[Supernal MCP] ✅ Tools loaded successfully');
  } catch (error) {
    console.error('[Supernal MCP] ⚠️  Could not load tools:', error.message);
    console.error('[Supernal MCP] Full error:', error.stack);
  }
}

async function main() {
  // Load tools before starting server (with silenced logs)
  await loadTools();
  
  // Restore console.log after tool loading
  console.log = originalLog;
  console.warn = originalWarn;

  const server = createSupernalMCPServer({
    name: '@supernal-interface/docs-site',
    version: '1.0.0',
    description: 'MCP server for @supernal-interface/docs-site tools'
  });

  const transport = createStdioTransport();

  console.error('[Supernal MCP] Starting server for @supernal-interface/docs-site...');

  try {
    await server.start(transport);
  } catch (error) {
    console.error('[Supernal MCP] Fatal error:', error);
    process.exit(1);
  }
}

// Graceful shutdown
process.on('SIGINT', () => {
  console.error('[Supernal MCP] Shutting down...');
  process.exit(0);
});

process.on('SIGTERM', () => {
  console.error('[Supernal MCP] Shutting down...');
  process.exit(0);
});

main();
